{% set name = "libsakura" %}
{% set version = "5.3.2" %}
{% set sha256 = "96de8b8f7cfdf5be29a3ac2b589231a712d70f0fb8f9a74ef316c22d60599bd3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tnakazato/sakura/archive/refs/tags/libsakura-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - compile-fixes.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - cmake <4
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - ninja
  host:
    - eigen
    - fftw

test:
  commands:
    - test -f $PREFIX/lib/libsakura$SHLIB_EXT
    - test -f $PREFIX/lib/pkgconfig/libsakura.pc
    - test -f $PREFIX/include/libsakura/sakura.h

about:
  home: https://tnakazato.github.io/sakura/
  license: LGPL-3.0-or-later
  license_file: libsakura/COPYING
  summary: 'C++ library for fast image manipulations'

extra:
  recipe-maintainers:
    - pkgw
