travis:
  secure:
    BINSTAR_TOKEN: bEg5BhW1HVoxKdZeaWoCnEr1LgypTPoCGi4EW6ebfUwDeLzn2DKMllzGmNdydEuDlQpIOuph+abwEYqC+fC/ldssDWB/teoci1fwWrg3NMfjBx9HJPrJVP0A6pJtp7lvnkTjE+Fg9ZtpheR+YKhj5EqgzKOmayyepumHciPUINQ7XZdB7Wyhr3BAcMPuPlO3xOHJKsUtLx+vd2ZVre73SXCXFAFy/uPu6m8/ygG8pLitf0GosRXXz80HFkpLg13Q9gyCX7bwJbP9OlMv2PtF/HLS+/fHWwhil9RSWz00/T4VEXA5ovjRx6btpScJB4IBog/+FuoR+E0YsxrBfgArAQOigAM7GyQlxoybKmsB0tvyiYqnDrz6bSuELkS9XhZmoKhQ+ZNgBv/x9lYcG0RbYNXev4VKpwRUc2ipmCwgpMzHZzYLlhrzY6RsO1y1GZuXCmZQK1sltI/p111AL+Pm48Ir/uzYzX8D1SADhXJHXjB76IOcQM+tQDlPAhcxbXuBAXmKJbioOZmu5pMeTvSoRJDWk1Ajyaz4CAtht9RBbuGWnyuwbzkHUVLOYd5taNa4SAdzyfLNdN++kHop1WN0Ix03lt+SN3tgjdlLxodD8gnuT/TFUX4nSr7J6AQNOIqMdErebC0kUbYNM49456ZStCSENI+sbHHLTdPOur/uOoM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
