travis:
  secure:
    BINSTAR_TOKEN: pBGDuHKi22BvaXAhYeb8Yd8KMpCTEvVXPRCp7odFe9jIWj/w428BwnV2xlUjCjmFhs6WdFjIRcjXtcK9MVGqWomgOTKNBVlCdCjLoxWfwtORt1vRVUGVLrjaN0Lg+hAX26DkQYgtGeZKMe7EfXdntrNe06jh5SqVpdT++J7x39A3g0WM7BQwsn54sykUQR7wVlq3Ubk5SsHZTC0cTZAdixKZKEUr60Tlv8FkK/3sSD6xxpjdWxVxSpFPQLqrQafRWq67nAmv6cuHsXwP3V+avNsJwzOwjJqQ9sXLdv92K/R0bqp4FZkEy08Nf+AdQa7W/rvupFLo4GlcC2zKZLqExyrjG47ohEUe0vAhcvFP8JJMF7H+GqaSXGteTU0wGQYsBQGjLPQxeW0RXEQGrSdjzRUDZhF6oonJQ9OK+U8siaiyKSeA5l3mQ6gnEZh8+q35Dfb+L7isqgfSloO2TDguShPtKoWdci1Aggme6ocZ6bCQJWF+IAyhJoedeOM3OD3Y2a6zBPO+L2RG+wn/+QEDvxrf3sxIPEXrIMVoPiAtk1j5DzJrFOB+ZFIE5bIsQqYfNX7mbFzccLL+3LjEKKoXu6jlOCV0ggRUNssNlgYRI8xwhl8w7LqEIFaMlfHUwbAh6iSo6PCy+XjCwxa7Q+6V3VoHMbXcsQy4DfeEY1e3SW0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
